import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
const binary = process.env.BROWSE_BIN || `${process.env.HOME}/.agents/skills/gstack/browse/dist/browse`;
const origin = process.env.PREVIEW_URL || 'http://127.0.0.1:4321';
const run = (...args) => execFileSync(binary, args, { encoding: 'utf8', maxBuffer: 5_000_000 }).trim();
const passed = [];
function assert(label, expression) {
  if (run('js', `Boolean(${expression})`) !== 'true') throw new Error(label);
  passed.push(label);
}
run('viewport','390x844');
run('goto',origin+'/join/');
assert('Signup button uses the requested label', 'document.querySelector("#signup button[type=submit]").textContent.trim()==="Join the Campaign"');
assert('Form buttons have no static callouts beneath them', '[...document.querySelectorAll(".campaign-form button[type=submit]")].every(button=>!button.nextElementSibling)');
assert('Footer includes the mayor commentary', '[...document.querySelectorAll(".footer-nav a")].some(a=>a.getAttribute("href")==="/bill-paparian/" && a.textContent.includes("Mayor"))');
run('click','.menu-toggle');
assert('Mobile menu opens', 'document.querySelector(".menu-toggle").getAttribute("aria-expanded")==="true"');
run('press','Escape');
assert('Escape closes menu and returns focus', 'document.querySelector(".menu-toggle").getAttribute("aria-expanded")==="false" && document.activeElement.matches(".menu-toggle")');
// Stub only the form transport: browser QA must never email campaign contacts.
run('js', `(()=>{window.__formRequests=[];window.__formStatus=503;const originalFetch=window.fetch;window.fetch=async(url,options)=>{if(url!=="/api/forms/")return originalFetch(url,options);window.__formRequests.push(JSON.parse(options.body));return new Response(JSON.stringify(window.__formStatus===200?{ok:true}:{error:"We couldn’t send this right now. Your entries are still here."}),{status:window.__formStatus,headers:{"Content-Type":"application/json"}})}})()`);
run('network','--clear');
run('click','#pledge button[type=submit]');
assert('Empty signup blocked','!document.querySelector("#pledge form").checkValidity() && !document.querySelector("#pledge .form-status").textContent');
for (const [name,value] of [['firstName','Preview'],['lastName','Tester'],['email','invalid-email'],['zip','12']]) run('fill',`#pledge input[name=${name}]`,value);
assert('Invalid email and ZIP blocked','!document.querySelector("#pledge input[name=email]").checkValidity() && !document.querySelector("#pledge input[name=zip]").checkValidity()');
run('fill','#pledge input[name=email]','preview@example.invalid');
run('fill','#pledge input[name=zip]','91101');
assert('Signup has five visible fields plus a spam trap', 'document.querySelectorAll("#pledge .form-grid input").length===5 && !document.querySelector("#pledge input[type=checkbox]")');
assert('Phone is optional', '!document.querySelector("#pledge input[name=phone]").required && document.querySelector("#pledge form").checkValidity()');
run('fill','#pledge input[name=phone]','123');
assert('Short phone number blocked','!document.querySelector("#pledge input[name=phone]").checkValidity()');
run('fill','#pledge input[name=phone]','2025550100');
run('click','#pledge button[type=submit]');
assert('Failed signup preserves entries and offers a retry','document.querySelector("#pledge .form-status").textContent.includes("couldn’t send") && document.querySelector("#pledge input[name=email]").value==="preview@example.invalid" && !document.querySelector("#pledge button").disabled');
run('js','window.__formStatus=200');
run('click','#pledge button[type=submit]');
assert('Successful signup confirms it was sent to Matt','document.querySelector("#pledge .form-status").textContent.includes("signup has been sent to Matt")');
assert('Retry keeps its submission ID','window.__formRequests[0].submissionId===window.__formRequests[1].submissionId');
assert('Signup resets all five fields','[...document.querySelectorAll("#pledge input")].every(input=>!input.value)');
run('click','#contact button[type=submit]');
assert('Empty contact form blocked','!document.querySelector("#contact form").checkValidity()');
run('fill','#contact input[name=name]','Preview Tester');
run('fill','#contact input[name=email]','preview@example.invalid');
run('select','#contact select[name=topic]','General question');
run('fill','#contact textarea','Preview validation test. Do not send.');
run('click','#contact button[type=submit]');
assert('Successful message confirms delivery to the campaign and clears fields','document.querySelector("#contact .form-status").textContent.includes("message has been sent to Matt") && !document.querySelector("#contact textarea").value');
assert('No personal data in URL or storage','!location.search && localStorage.length===0 && sessionStorage.length===0');
const formNetwork = run('network');
writeFileSync('.context/form-network.txt', formNetwork);
assert('Both forms post the right kind and fields to the email endpoint','window.__formRequests.length===3 && window.__formRequests[1].kind==="signup" && window.__formRequests[2].kind==="contact" && window.__formRequests[2].message.includes("Do not send")');
if (formNetwork !== '(no network requests)') throw new Error('Mocked form test emitted an unexpected network request');
passed.push('Browser QA sends no real submissions');
run('goto',origin+'/facts/');
assert('All FAQs start collapsed','document.querySelectorAll("details").length===13 && document.querySelectorAll("details[open]").length===0');
run('click','#what-is-measure-pfd summary');
assert('FAQ opens by click','document.querySelector("#what-is-measure-pfd").open');
run('press','Enter');
assert('FAQ closes from keyboard','!document.querySelector("#what-is-measure-pfd").open');
run('goto',origin+'/');
run('press','Tab');
assert('Keyboard starts at skip link','document.activeElement.matches(".skip-link")');
run('press','Enter');
assert('Skip link moves focus into main','document.activeElement.matches("#main")');
assert('Footer share button removed', '!document.querySelector(".site-footer .share-button")');
run('click','.tax-amount a');
assert('Tax estimate link reaches its visible footnote', 'location.hash==="#tax-estimate-note" && document.querySelector(location.hash).textContent.includes("median sales price")');
assert('Mobile bar contains only the Vote NO action','!document.querySelector(".mobile-pledge > span") && document.querySelector(".mobile-pledge a").textContent.trim()==="Vote NO" && document.querySelector(".mobile-pledge a").getAttribute("href")==="/join/#signup"');
assert('Header, hero, and closing prioritize Vote NO','["#main-navigation a:last-child", ".hero-actions .button", ".closing .button"].every(selector=>{const a=document.querySelector(selector);return a?.textContent.trim()==="Vote NO" && a.getAttribute("href")==="/join/#signup"})');
run('click','.hero-actions a[href="/join/#signup"]');
assert('Homepage Vote NO action reaches the signup form','location.pathname==="/join/" && location.hash==="#signup" && !!document.querySelector("#pledge form")');
run('click','.footer-nav a[href="/vote/"]');
assert('Footer voting link opens the guide','location.pathname==="/vote/" && document.querySelector("h1").textContent.includes("How to vote")');
assert('Voting tools are available without a campaign form','!document.querySelector("form") && document.querySelectorAll(".voting-step").length===4');
assert('Official voting links open new tabs','[...document.querySelectorAll(".voting-guide a[href^=https],.voting-sources a[href^=https]")].every(a=>a.target==="_blank" && a.rel.includes("noopener"))');
run('goto',origin+'/facts/');
run('click','#how-to-vote');
assert('How-to-vote resource reaches the guide','location.pathname==="/vote/"');
run('click','.mobile-pledge a');
assert('Mobile Vote NO action reaches signup from the guide','location.pathname==="/join/" && location.hash==="#signup" && !!document.querySelector("#pledge form")');
writeFileSync('.context/interaction-audit.json',JSON.stringify(passed,null,2));
console.log(`Passed ${passed.length} interaction checks.`);
