import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
const binary = process.env.BROWSE_BIN || `${process.env.HOME}/.agents/skills/gstack/browse/dist/browse`;
const origin = process.env.PREVIEW_URL || 'http://127.0.0.1:4321';
const run = (...args) => execFileSync(binary, args, { encoding: 'utf8', maxBuffer: 5_000_000 }).trim();
const passed = [];
function assert(label, expression) {
  if (run('js', `Boolean(${expression})`) !== 'true') throw new Error(label);
  passed.push(label);
}
run('viewport','390x844');
run('goto',origin+'/join/');
run('click','.menu-toggle');
assert('Mobile menu opens', 'document.querySelector(".menu-toggle").getAttribute("aria-expanded")==="true"');
run('press','Escape');
assert('Escape closes menu and returns focus', 'document.querySelector(".menu-toggle").getAttribute("aria-expanded")==="false" && document.activeElement.matches(".menu-toggle")');
run('network','--clear');
run('click','#pledge button[type=submit]');
assert('Empty signup blocked','!document.querySelector("#pledge form").checkValidity() && !document.querySelector("#pledge .form-status").textContent');
for (const [name,value] of [['firstName','Preview'],['lastName','Tester'],['email','invalid-email'],['zip','12']]) run('fill',`#pledge input[name=${name}]`,value);
assert('Invalid email and ZIP blocked','!document.querySelector("#pledge input[name=email]").checkValidity() && !document.querySelector("#pledge input[name=zip]").checkValidity()');
run('fill','#pledge input[name=email]','preview@example.invalid');
run('fill','#pledge input[name=zip]','91101');
run('click','#pledge input[name=sms]');
assert('Phone required when text updates selected','document.querySelector("#pledge input[name=phone]").required && !document.querySelector("#pledge form").checkValidity()');
run('fill','#pledge input[name=phone]','123');
assert('Short phone number blocked','!document.querySelector("#pledge input[name=phone]").checkValidity()');
run('fill','#pledge input[name=phone]','2025550100');
run('click','#pledge button[type=submit]');
assert('Valid signup gives honest preview feedback','document.querySelector("#pledge .form-status").textContent.includes("Nothing was sent or saved")');
assert('Signup resets data and consent','!document.querySelector("#pledge input[name=email]").value && !document.querySelector("#pledge input[name=sms]").checked && !document.querySelector("#pledge input[name=phone]").required');
run('click','#contact button[type=submit]');
assert('Empty contact form blocked','!document.querySelector("#contact form").checkValidity()');
run('fill','#contact input[name=name]','Preview Tester');
run('fill','#contact input[name=email]','preview@example.invalid');
run('select','#contact select[name=topic]','General question');
run('fill','#contact textarea','Preview validation test. Do not send.');
run('click','#contact button[type=submit]');
assert('Valid contact preview clears data','document.querySelector("#contact .form-status").textContent.includes("Nothing was sent or saved") && !document.querySelector("#contact textarea").value');
assert('No personal data in URL or storage','!location.search && localStorage.length===0 && sessionStorage.length===0');
writeFileSync('.context/form-network.txt',run('network'));
run('goto',origin+'/facts/');
run('click','.faq-item:nth-child(2) summary');
assert('FAQ opens by click','document.querySelectorAll(".faq-item")[1].open');
run('press','Enter');
assert('FAQ closes from keyboard','!document.querySelectorAll(".faq-item")[1].open');
run('goto',origin+'/');
run('press','Tab');
assert('Keyboard starts at skip link','document.activeElement.matches(".skip-link")');
run('press','Enter');
assert('Skip link moves focus into main','document.activeElement.matches("#main")');
run('click','.share-button');
assert('Share copy fallback returns useful status','document.querySelector(".share-status").textContent.includes("Link copied") || document.querySelector(".share-status").textContent.includes("Copy this link")');
writeFileSync('.context/interaction-audit.json',JSON.stringify(passed,null,2));
console.log(`Passed ${passed.length} interaction checks.`);
